// <auto-generated />
using System;
using Advance_SQL_SERVER_with_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Advance_SQL_SERVER_with_API.Migrations
{
    [DbContext(typeof(StudentDBcontext))]
    [Migration("20240228173802_InitialSchoolDB")]
    partial class InitialSchoolDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Advance_SQL_SERVER_with_API.Data.Student", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            id = new Guid("2bd9e348-924e-485c-8265-913449564e15"),
                            age = 21,
                            name = "Test"
                        },
                        new
                        {
                            id = new Guid("fff351b6-14f2-4e01-945d-398a92800d6d"),
                            age = 22,
                            name = "Test2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
